version: '3.3'

services:
  Mysql5.7_c:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  PHP5.6_c:
    image: php:5.6-apache
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
